### ISSUE TITLE
Implement `Comparable`

### ISSUE THREAD

**Issue by shilangyu** [mzdm/iso_duration_parser#17]
Make `IsoDuration` implement `Comparable`. I am happy to send a PR with this if you like.

**Comment by mzdm** [comment]
yes PRs are welcomed ❤️

**Comment by shilangyu** [comment]
Actually, since `IsoDuration` is inherently an imprecise measurement, it cannot implement `Comparable` since `Comparable` has to be always well-defined. My bad!
